spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.1.150
    port: 6379
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 10s

mybatis:
  mapper-locations: classpath:mapper/*.xml